

```{r}
# if (!requireNamespace("BiocManager", quietly = TRUE))
#     install.packages("BiocManager")
# BiocManager::install("scDblFinder")
#BiocManager::install("zellkonverter")
#install.packages('zellkonverter')
```

```{r}
library(scDblFinder)
library(zellkonverter)
library(SingleCellExperiment)
library(BiocParallel)
```
## Read data
```{r}
dat=readH5AD('../data/data_RBC_removed.h5ad')
```

## Rename AssayName from 'X' to 'counts', as this is necessary for scDblFinder to run
```{r}
names(dat@assays)='counts'
```

## Run scDblFinder

```{r}
## Cluster data with fastcluster 
dat$cluster <- fastcluster(dat)

## Setting BiocParallel parameters (num of parallel threads + set seed)
bp<-MulticoreParam(3, RNGseed=1234)

## 1. Run scDblFinder -> as muliple batches were run, tell scDblFinder which samples were in one batch
## 2. Set cluster to True 
#  (see details: http://bioconductor.org/books/3.15/OSCA.advanced/doublet-detection.html
#                https://bioconductor.org/packages/release/bioc/vignettes/scDblFinder/inst/doc/scDblFinder.html)

sce <- scDblFinder(dat,samples='patient',cluster=TRUE,BPPARAM=bp)
```

## Save file as .h5ad file
```{r}

## Set name of assay back to 'X' -> for scanpy analysis later
names(sce@assays)='X'

## Save file
writeH5AD(sce,file='../data/prelim_analysis_with_doublet_scores.h5ad')
```

