FROM ubuntu:22.04
ARG RELEASE
ARG LAUNCHPAD_BUILD_ARCH
LABEL org.opencontainers.image.ref.name=ubuntu
LABEL org.opencontainers.image.version=22.04
#ADD file:63d5ab3ef0aab308c0e71cb67292c5467f60deafa9b0418cbb220affcd078444 in / 
CMD ["/bin/bash"]
RUN apt-get update && apt-get install -y build-essential # buildkit
RUN apt-get install -y wget # buildkit
RUN wget https://github.com/kharchenkolab/Baysor/releases/download/v0.6.2/baysor-x86_x64-linux-v0.6.2_build.zip # buildkit
RUN apt-get install -y zip unzip # buildkit
RUN unzip baysor-x86_x64-linux-v0.6.2_build.zip # buildkit
RUN ln -s /bin/baysor/bin/baysor /usr/local/bin/baysor # buildkit
RUN apt-get install -y python3 python3-pip vim # buildkit
RUN pip3 install pandas pyometiff # buildkit
ENTRYPOINT ["/bin/bash", "-l", "-c"]
